# Cribbed from https://github.com/GTNewHorizons/RetroFuturaGradle/blob/b88ad16629fa26ebc8c918ea26ced18502a2c4e9/.github/workflows/build-and-test.yml
name: Build

on:
  push:
    branches: [ master, main ]
  release:
    types: [ published ]

jobs:
  build-and-test:
    name: "Pre release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDKs
      uses: actions/setup-java@v3
      with:
        java-version: |
          8
          17
        distribution: 'zulu'
        cache: gradle

    - name: Build the mod
      run: bash ./gradlew build

    - name: Release the artifact
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: ${{ steps.vars.outputs.sha_short }}
          files: |
            build/libs/*.jar
